### ISSUE TITLE
JDBC-Yugabytedb is getting issue

### ISSUE THREAD

**Issue by jainisking** [yugabyte/jdbc-yugabytedb#1]
Caused by: java.lang.IncompatibleClassChangeError: Class com.yugabyte.driver.core.policies.PartitionAwarePolicy does not implement the requested interface com.datastax.driver.core.policies.LoadBalancingPolicy
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1775) ~[cassandra-driver-core-3.8.0-yb-5.jar:na]
	at com.datastax.driver.core.Cluster.init(Cluster.java:216) ~[cassandra-driver-core-3.8.0-yb-5.jar:na]
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:389) ~[cassandra-driver-core-3.8.0-yb-5.jar:na]
	at com.datastax.driver.core.Cluster.connect(Cluster.java:340) ~[cassandra-driver-core-3.8.0-yb-5.jar:na]
	at org.springframework.data.cassandra.config.CassandraCqlSessionFactoryBean.connect(CassandraCqlSessionFactoryBean.java:90) ~[spring-data-cassandra-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.cassandra.config.CassandraCqlSessionFactoryBean.afterPropertiesSet(CassandraCqlSessionFactoryBean.java:82) ~[spring-data-cassandra-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.data.cassandra.config.CassandraSessionFactoryBean.afterPropertiesSet(CassandraSessionFactoryBean.java:59) ~[spring-data-cassandra-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 205 common frames omitted

**Comment by jainisking** [comment]
After you "jdbc-yugabytedb" instead of "postgresql" driver, getting the above issue. and when using "postgresql" data is not distributing in all nodes.
